package data.database.entities

import androidx.room.DatabaseView

/**
 * Read model that unifies the `core_words` and `user_words` tables.
 *
 * `WordEntity` is no longer backed by a single table. Instead it is a
 * [DatabaseView] over `words_view`, which is created by the
 * `MIGRATION_3_4` migration as a `UNION ALL` of the two underlying
 * tables. The `source` column is a literal projected by the view
 * (`'core'` or `'user'`) and lets the rest of the app keep using
 * `WordEntity.isUserAdded()` and the `Mine` tab filter without ever
 * touching the underlying table split.
 *
 * Phase 1 keeps the schema intentionally flat so it can be persisted
 * with two sibling tables plus a handful of converters; no relations
 * are required.
 */

// region: View definition
/**
 * SQL body of the `words_view` UNION ALL. Declared as a top-level
 * `const val` so the `@DatabaseView` annotation and the
 * `MIGRATION_3_4` migration share the exact same string. Room
 * compares the SQL produced by the migration against the SQL it
 * expects from the annotation verbatim, so any divergence in
 * whitespace, line breaks or quoting breaks schema validation; the
 * shared constant guarantees they stay in sync.
 */
const val WORDS_VIEW_BODY: String =
    "SELECT 'core' AS source, id, word, translation, type, regular, forms, pronunciation, category, synonyms, antonyms, examples, tags, difficulty, status, level, favorite, notes, reviewCount, lastReview, nextReview, customDifficulty\n" +
        "        FROM core_words\n" +
        "        UNION ALL\n" +
        "        SELECT 'user' AS source, id, word, translation, type, regular, forms, pronunciation, category, synonyms, antonyms, examples, tags, difficulty, status, level, favorite, notes, reviewCount, lastReview, nextReview, customDifficulty\n" +
        "        FROM user_words"
// endregion

// region: WordEntity
/**
 * Room view that represents a single dictionary word along with the
 * learning state owned by the user.
 *
 * The primary key ([id]) is auto-generated by the underlying table
 * (`core_words` or `user_words`) and is unique within that table. The
 * UI never persists this class directly — writers use
 * [CoreWordEntity] / [UserWordEntity] and read flows consume
 * [WordEntity].
 *
 * Dictionary fields are immutable for a given word; the trailing fields
 * (`favorite`, `learned`, `notes`, `reviewCount`, `lastReview`,
 * `nextReview`, `customDifficulty`) are user-owned and mutated by the
 * feature layer (Phase 3+).
 */
@DatabaseView(
    viewName = "words_view",
    value = WORDS_VIEW_BODY
)
data class WordEntity(
    /**
     * Origin discriminator synthesised by the view. Always one of
     * [SOURCE_CORE] or [SOURCE_USER]. Never persisted as a column on
     * either underlying table.
     */
    val source: String,
    val id: Int,
    val word: String,
    val translation: String,
    val type: String,
    val regular: Boolean?,
    val forms: Forms?,
    val pronunciation: Pronunciation?,
    val category: List<String>?,
    val synonyms: List<String>?,
    val antonyms: List<String>?,
    val examples: List<Example>?,
    val tags: List<String>?,
    val difficulty: Difficulty,
    /**
     * Tri-state learning progress. Promoted by the user through the
     * status button on each [WordCard] and stored on either underlying
     * table as TEXT.
     */
    val status: LearningStatus = LearningStatus.NOT_LEARNED,
    /**
     * Progression bucket. Independent from [difficulty]; controls
     * when the word becomes available in mini-games.
     */
    val level: Int = 1,
    val favorite: Boolean = false,
    val notes: String = "",
    val reviewCount: Int = 0,
    val lastReview: Long? = null,
    val nextReview: Long? = null,
    val customDifficulty: Difficulty? = null
) {
    companion object {
        /** Source value used for entries seeded from `assets/words.json`. */
        const val SOURCE_CORE: String = "core"

        /** Source value used for entries the user added through the app. */
        const val SOURCE_USER: String = "user"
    }
}

/**
 * Returns `true` when the word was added by the user rather than seeded
 * from the bundled dictionary asset.
 *
 * Used by the UI to gate destructive actions (delete) on user-owned rows
 * and by the future DAO layer to enforce the same restriction at the
 * data tier.
 */
fun WordEntity.isUserAdded(): Boolean = source == WordEntity.SOURCE_USER
// endregion

// region: Nested value classes
/** Verb conjugation forms; nullable because adjectives/nouns do not have them. */
data class Forms(
    val base: String?,
    val thirdPerson: String?,
    val presentParticiple: String?,
    val pastSimple: String?,
    val pastParticiple: String?
)

/** IPA transcription plus optional audio asset reference. */
data class Pronunciation(
    val ipa: String?,
    val audio: String?
)

/** Bilingual example sentence tagged with a CEFR level (A1, A2, B1, …). */
data class Example(
    val english: String,
    val spanish: String,
    val level: String
)
// endregion

// region: Difficulty enum
/**
 * Coarse learning difficulty used for both the dictionary baseline
 * ([WordEntity.difficulty]) and the user-defined override
 * ([WordEntity.customDifficulty]).
 */
enum class Difficulty {
    EASY,
    MEDIUM,
    HARD;

    companion object {
        /**
         * Parses a [String] into a [Difficulty].
         *
         * @param value Case-insensitive enum name, or null.
         * @return The matching [Difficulty], or null when the value is
         *   null or not part of the enum.
         */
        fun fromStringOrNull(value: String?): Difficulty? =
            value?.let { runCatching { valueOf(it.uppercase()) }.getOrNull() }

        /**
         * Same as [fromStringOrNull] but falls back to [default] when the
         * value cannot be parsed. Useful when seeding legacy data where
         * unknown difficulty labels should not crash the import.
         *
         * @param value Raw string coming from JSON or the database.
         * @param default Difficulty to use when [value] is unrecognised.
         */
        fun fromStringOrDefault(value: String?, default: Difficulty = MEDIUM): Difficulty =
            fromStringOrNull(value) ?: default
    }
}
// endregion